seekhealing/seekhealing.github.io

index.html

Updated hero unit text.

---

index.html

Change text on bottom of homepage.

---

css/custom.css
why-we-care.html

Fixes to why-we-care content and layout.

---

index.html

This is a simple pull request that fixes #42 that merely updates the "Donate Today" link on the home page to the link outlined in the issue.

Content: Updating donate link on home page

---

science-of-connection.html

This PR is a partial fix for #12 .  
The only item in the issue that is not completed is:
> Below "A Spark was Lit" section, please add an "Additional Resources section" and include the following links
American Carnage article
PDF's in the external lit research folder of the shared google drive
[ ] - I have requested additional information to complete that item.
All of the other items were completed, however, and the screen cap below illustrates how these changes look in my local dev environment:
<kbd>
</kbd>

Content: Updates for science-of-connection page

---

_includes/nav.html
financials.html

This PR fixes #33 which is to create a simple placeholder page for upcoming financials information.

Content: Adding financials page

---

_config.yml
css/custom.css
index.html

This PR includes content changes (mostly...) that were requested in #32.
I wasn't completely clear what a few items meant, but did my best to do them as I thought best.  Below are line items of each requested item and a screen cap of before/after the edits.
> change "not a cure" to "rethink rehab" (shows up in the page title on the tab, when you link it, etc)
I assume this meant the page title, or really even the part of the title that appears on EVERY page?  
So, that change was made in the `_config.yml` file which is a good place to keep something like that.
> **change:**
Unlocking the benefits of authentic connection experiences to empower sustainable healing after detox from heroin & opioid addiction.
**to:**
Detox aftercare services that liberate human beings from opioid addiction …

Content: Changes for Home Page

---

css/custom.css
they-were-here.html

This PR fixes #53 by adding Matthew to the memorial wall on the They Were Here page.

Content: Adding Matthew to memorial wall

---

css/custom.css
css/responsive.css
index.html
js/functions.js
our-programs.html

This PR fixes items 1 through 4 of #58.  The only item this PR doesn't address in #58 is adding the mailchimp newsletter form.
- Removing the laughing girl pic, fundraising text, and changing the "For more information..." text was straightforward.
- Moving the Donate button into the hero and making it more prominent required more substantial styling and html structural changes.  In doing so, I also tried to make this section better for mobile users as well so you will see some changes for mobile there too.
- This also adds the personal stories to the bottom of the page.  Ideally, these were to be contained in bubbles, but I wasn't sure what exactly that meant or if there was any design in mind, so used some existing elements and tweaked them for this section.  If a different design was …

Design & Content changes for home page

---

css/custom.css
they-were-here.html

Content: Memorial wall addition

---

index.html

This PR includes a minor content change per the latest slack conversation for the home page.  It was requested to update the hero content from:
> Be a part of the solution to the American opioid epidemic
to:
> Be a part of the solution to the opioid epidemic in the Mid-Atlantic US

Content: Home Page Hero Content Update

---

they-were-here.html

This PR fixes #72 
Very quick content addition to the Memorial wall.

Content: Addition to memorial wall

---

_includes/nav.html
connection-agents.html
css/custom.css
js/custom-functions.js

This PR fixes #31.
In order to minimize effort, this is a pretty bare bones HTML form that submits to a Google Form where collaborators will be notified upon new submissions.  I have added kyla@seekhealing.org as a collaborator to the google form I created, if others would like to be added I can add them.  **Please Note** - this form is under my personal google account.  If you would like the form transitioned to a different account, please let me know and we can make a copy of it elsewhere if desired.
I did include form validation for required fields and email addresses.  I didn't include any form validation for phone number and zip code, or field lengths as I'm not sure what formats and lengths were desired.  If we want any additional validation on the form please let me know.
Also, per …

Feature: Addition of the connection agent registration form

---

css/custom.css
index.html

This PR fixes #69 which was just a quick content change.  It does also add a CSS class for formatting a word as bold/purple too per the issue.

Content: Home Page Content Update

---

css/custom.css
volunteer.html

This PR fixes #74 to update the content on the Volunteer page.  A few new styles needed to be added for the bulleted list and purple/italic text.  Other than that pretty straight forward update.  
Screen cap below to view updates:

Content: Updates to volunteer page

---

css/custom.css
our-programs.html

This PR fixes #59 which includes several content updates including adding an embedded youtube video as well as removing some components that had specific styling added including the purple boxes and red outline box.
Below are some screen captures of the new page on desktop and mobile to view as well:

Feature: Programs Page Content Updates

---

css/custom.css
index.html

This PR fixes #82 that included a couple of home page updates outlined below:
- "About Seekhealing" sentence link addition
- style fixes for subscribe form (see before/after screenshots below)
- new Asheville pilot program 2018 section

Content: Home Page Content Changes

---

_data/contact.yaml
_includes/sections/locations.html

This PR fixes #97 which included a few contact-us page updates.
Everything is pretty straight-forward for these updates.  I did need to tweak the layout to make the locations layout on the contact-us page a little more balanced, but nothing major.

Contact: Updates to contact us page

---

_sections/triple-columns/triple-col-pilot-ctas-2.md

This PR addresses #112 that called for a simple date change on the home page.

Content: Updating listening training dates on home page

---

_data/asheville-pilot-program.yaml
_layouts/custom-asheville.html

This PR addresses the content changes in #91.
Very straight-forward request I think.  Below is a screen cap of how the new content looks on desktop:

Content: Changes to Asheville pilot program page

---

_data/directors.yaml
_sections/team/jennifer-nicolaisen.md
_sections/team/joshua-ginsberg.md
_sections/team/kyla-trainor.md
_sections/team/rachel-wurzman.md

This PR addresses #116 that included a few content change requests.  These changes are all in content files, so nothing special to point out here.  Below is screen capture of new content on the page:

CONTENT: Updates to the board of directors page

---

_sections/triple-columns/triple-col-pilot-ctas-2.md

This PR addresses #140 which is a quick and simple text change on the home page.

Content: Quick button text change on home page

---

_sections/subnav/board-of-directors.md
_sections/subnav/financials.md
_sections/subnav/press.md
_sections/subnav/team.md

Removed subtitles from About page.

---

_data/contact.yaml
_includes/sections/boxes.html
_includes/sections/connect.html
_sass/components/_locations.scss

Updates to contact page

---

_pages/they-were-here.md

Change text/link on memorial wall

---

_includes/sections/connection-agent-form.html
_sections/connection-agent-form/connection-agent-form.md

Fixes to connection agent page.

---

_sections/single/general-volunteering.md
_sections/single/listeners.md

Fixes to volunteer page.

---

_data/resources.yaml
_includes/sections/resources.html

Fixes #148.
This PR includes new items on the Additional Resources page as requested in #148.
One note is I used the book font awesome icon as opposed to the book image in the issue.  Seems like that was just a suggestion, but for consistency, organization, and page load purposes, I feel like the font awesome icon would be best.  If the icon in the ticket is preferred, we can add it.

Content: Adding new items to Additional Resources page

---

_sections/double-columns/rehab-narrative-col-2.md

Fixes #147.
This PR includes a small content change for the Rethinking Rehab page as requested in #147.

Content: Changes to Rethinking Rehab page

---

_pages/why-we-care.md
_sections/double-full/why-ambulance.md
_sections/double-full/why-drugs.md
_sections/parallax/why-because.md
_sections/single/overdose-deaths.md
_sections/single/why-are-we-doing-this.md
_sections/single/why-data.md
_sections/single/why-report.md

Fixes #146.
This PR includes content changes for the Why We Care page as requested in #146.

Content: Changes to Why We Care page

---

_sections/single/listening-training-authetic-connection.md

Fixes #188.
This PR removes the parenthetical phrase for adding the link to /heal/ with the actual link.

Content Bug: Fixing parenthetical link to be an actual link

---

_data/directors.yaml
_includes/sections/directors.html
_pages/board-of-directors.md
_sections/directors/joshua-ginsberg.md
_sections/directors/kyla-trainor.md
_sections/directors/rachel-wurzman.md
_sections/subnav/board-of-directors.md

Content: Reverting previous changes to board page

---

_data/header.yaml

Content: Adding "how to" to Heal top navigation submenu

---

_data/memorial-wall.yaml

Per slack conversation, this PR adds Michael Marro to the Memorial wall.

Content: Adding Michael Marro to wall

---

_sections/events/2019-04-20-listening-training.md

Fixes the April Listening Training RSVP button link per https://seekhealing.slack.com/archives/CE76SU751/p1549376947000500.

Content: Fixing April Listening Training RSVP Link

---

_data/memorial-wall.yaml

This PR adds Eric Dandy to the memorial wall per https://seekhealing.slack.com/archives/CE76SU751/p1549894269004200.

Content: Wall additions

---

_sections/single/extra-care-program.md
_sections/single/extra-care-qualifications.md

This PR contains content edits for the Extra Care Program Page per this slack conversation: https://seekhealing.slack.com/archives/CE76SU751/p1550264391002100

Content: Extra Care Program Page Updates

---

_data/header.yaml

This PR adjusts the order of the HEAL dropdown navigation order per https://seekhealing.slack.com/archives/CE76SU751/p1551227449004300.

Content: HEAL Menu Order Changes

---

_data/global.yaml
_includes/sections/events.html
_pages/upcoming-events.md
_sass/layouts/_articles.scss
_sections/single/upcoming-events-blurb.md

This PR contains a content update to add some qualifying text for the end user explaining upcoming events and linking to the Asheville Program page with the calendar.  This request is per: https://seekhealing.slack.com/archives/CE76SU751/p1551311450005500

Content: Upcoming Events qualifying text addition

---

_includes/sections/press.html
_sass/components/_press.scss
_sections/press/2018-10-03-overdose-awareness-day.md

This PR adds the new video link as requested [here](https://seekhealing.slack.com/archives/CE76SU751/p1551317517001000) to the Press page.  As this is a youtube video link, I also created the embed video feature for Press articles as well to accompany this request.

Adding video capability & article to Press page

---

_data/memorial-wall.yaml
_includes/sections/memorial-wall.html
_sass/components/_lists.scss

This PR adds the ability to combine "remembered by" people for one person and fixes the content on the memorial wall per: https://seekhealing.slack.com/archives/CE76SU751/p1554085044000900

Feature: Consolidating Memorial Wall Entries

---

_sections/single/addiction-video.md

Updates the youtube video on the /learn page per: https://seekhealing.slack.com/archives/CE76SU751/p1556205104000300

Content: Updating video on learn page

---

_sections/resources/resources.md

Adds a video to the top of the Additional Resources Page per: https://seekhealing.slack.com/archives/CE76SU751/p1556205197000900

Content: Adding video to resources page

---

_sections/events/2019-02-12-opioid-addiction-101.md
_sections/events/2019-04-20-listening-training.md
_sections/events/2019-04-23-opioid-addiction-101.md
_sections/events/2019-06-19-opioid-addiction-101.md
_sections/events/2019-07-17-opioid-addiction-101.md
_sections/events/2019-08-21-opioid-addiction-101.md
_sections/events/2019-09-18-opioid-addiction-101.md
_sections/events/2019-10-16-opioid-addiction-101.md

This PR adds new OA101 events and cleans up old events while I was going in there per: https://seekhealing.slack.com/archives/CE76SU751/p1556636121000800

Content: Adding new OA101 events

---

_sections/double-full/rehab-challenge.md
_sections/double-full/rehab-pain.md
_sections/double-full/rehab-transition.md

This PR accomplishes the minor content changes to the "Rethink Rehab" page in the May 2019 Website Updates as detailed [here](https://docs.google.com/document/d/1m4dQ3hz6Rgy3GcJH-0a0VB_Gc55XgGNBJw1Cq4C2bvM/edit#heading=h.fjoylwa76gyo).

May 2019 Updates: Rethink Rehab page updates

---

_includes/sections/single.html
_pages/harm-reduction.md
_sass/components/_lists.scss
_sections/single/harm-reduction-story.md
_sections/single/harm-reduction-summary.md

Contains requested content & styling changes from these Slack conversations:
https://seekhealing.slack.com/archives/CE76SU751/p1560353486002400
https://seekhealing.slack.com/archives/CE76SU751/p1560353535003100
Desktop view with new left-aligned styling:

Content & Styling: Updates to Harm Reduction page

---

_sections/single/why-are-we-doing-this.md

Includes a couple of styling fixes as documented in the below conversations:
https://seekhealing.slack.com/archives/CE76SU751/p1560630228000500
https://seekhealing.slack.com/archives/CE76SU751/p1560630237000800

Styling: Why We Care page styling fixes

---

_data/contact.yaml
_includes/sections/boxes.html

This PR accomplishes the changes to the Contact page in the May 2019 Website Updates as detailed [here](https://docs.google.com/document/d/1m4dQ3hz6Rgy3GcJH-0a0VB_Gc55XgGNBJw1Cq4C2bvM/edit?ts=5cf92b1a#heading=h.l0n0ic2jmyhs).

May 2019 Updates: Contact page updates

---

_sections/double/gabor-quote.md
_sections/single/addiction-maladaption.md
_sections/single/home-asheville.md

This PR contains 2 minor styling fixes requested in the following Slack conversations:
https://seekhealing.slack.com/archives/CE76SU751/p1561044113001100
https://seekhealing.slack.com/archives/CE76SU751/p1561044182001500

Styling fixes on Home & Science of Connection pages

---

_data/header.yaml

This PR makes the "Program Sign-Up" external link in the header open in a new tab/window per the "July 2019 Cleanup Edits" document.

July 2019 Updates: Menu

---

_sections/single/how-it-works.md

This PR completes the edits requested in the "July 2019 Cleanup Edits" document for the Heal(/heal/) page that include the following:
1. Please change:
“Whether you’re in recovery, trying to change a substance use pattern, want to volunteer, want to offer your business services seekers, or just want to live a more connected life, click the button above to get started.” 
To:
“Whether you’re in recovery, trying to change a substance use pattern, want to volunteer, want to offer a service or activity, or just want to live a more connected life, click the button below to get started.” 
2. And then, please move that same sentence to be above the button. 
3. Please make the other sentence (“You’ll fill out a short form…”) the italicized caption for the button. Please remove “Currently only …

July 2019 Updates: Heal page

---

_includes/sections/directors.html
_sections/directors/andrew-weil.md
_sections/directors/bill-white.md
_sections/directors/gabor-mate.md
_sections/directors/hilary-jacobs-hendel.md

This PR updates the links on the Leadership page per Slack conversation (https://seekhealing.slack.com/archives/CE76SU751/p1566383278001700) by:
1. Adding Hillary's website
2. Making the names links

Content: Updating website links on Leadership page

---

_sections/double-full/why-drugs.md

This PR contains a small content change that changes the content:
from: 
> “It is now estimated that nearly 140 people die every day from opioid-related overdoses.”
to 
> “It is now estimated that nearly 130 people die every day from opioid-related overdoses.”
and now links too: https://www.cdc.gov/drugoverdose/epidemic/index.html
per https://seekhealing.slack.com/archives/CE76SU751/p1568390955000600

Content: Sept 2019 content change to Why We Care page

---

_sass/base/_typography.scss
_sections/double-columns/sponsor-parts-1.md
_sections/double-columns/sponsor-parts-2.md

This PR contains 1 content change per slack conversation here:
https://seekhealing.slack.com/archives/CE76SU751/p1569768249001000
And 1 styling tweak to make the link a different color to be more easily seen on the black background per the slack conversation here:
https://seekhealing.slack.com/archives/CE76SU751/p1569768269001400

Content: Homepage content & style change

---

_sections/hero/home.md

This PR changes the hero button's donate link to another campaign per this Slack conversation: 
https://seekhealing.slack.com/archives/CE76SU751/p1572446681000700
**Please note, there are lot of other donate buttons, but I'm assuming the others stay the same?

Content: Updating Home page hero donate button link

---

_data/memorial-wall.yaml

Adds Kay Hemp to the Memorial Wall page per: https://seekhealing.slack.com/archives/CE76SU751/p1578931799002700

Content: Adding Kay Hemp to the Memorial Wall

---

_data/header.yaml
_sass/base/_typography.scss
_sass/layouts/_footer.scss
_sections/double-columns/sponsor-parts-1.md
_sections/double-columns/sponsor-parts-2.md

Removing link to /oa101 until page is ready.
This also resolves a hover styling inconsistency.

Nav link hotfix

---

_sections/events/watm-festival/2020-06-12-2130-dance-like-nobodys-watching.md
_sections/events/watm-festival/2020-06-14-1200-hear-me-open-hearted-open-mic.md

- Two event description tweaks

Minor edits

---

_includes/sections/hero.html
_includes/sections/webinar-schedule.html
_sass/layouts/_heros.scss
_sections/hero/obt-hero.md
_sections/webinar-events/obt/2020-12-05-13-30-humanizing-automation-technologys-role-in-social-health.md
_sections/webinar-events/obt/2020-12-05-19-30-illness-and-health-in-an-insane-culture.md

This fixes a broken image link and adds dynamic events w/ links to their Zoom rooms to the OBT hero.

Add dynamic event blocks to OBT hero

---

_includes/sections/hero.html
_includes/sections/webinar-schedule.html
_includes/widgets/addtocalendar.html
_sass/components/_buttons.scss
_sass/layouts/_heros.scss
_sections/hero/obt-hero.md
_sections/single/design-credit.md
_sections/single/obt-intro.md
_sections/webinar-schedules/obt-schedule.md

This updates event block buttons in the same manner as the hero for clarity/consistency and ease of navigation.

Update all OBT event buttons dynamically

---

_data/header.yaml
_sass/components/_boxes.scss
_sections/webinar-events/obt/2020-12-04-19-30-relating-languages.md
_sections/webinar-events/obt/2020-12-05-12-00-making-room-for-emotions.md

Last-minute OBT edits
