index.html

This update fixes #43 by adding:
- the information packet to a `downloads` directory that can be used to house other downloadable content pdfs, docs, ppts, etc.
- a link to the pdf at the bottom of the home page per the issue that says, "For more information about SeekHealing".
Below screen cap is how it all looks:

Content: Adding information packet & link

---

_includes/nav.html
guidance-for-detox.html
seekconnection.html

This pull request fixes #30.
The updated ask for this issue, as I understand it, was to update the top nav and 2 new placeholder pages to the site.
The top nav verbage was updated in the `_includes/nav.html` file and added 2 new placeholder, flat HTML pages to the root of the site.  One for "Guidance for Detox" and one for "SeekConnection".  Below is a screen cap of the new menu structure and an example of the "Coming Soon" placeholder pages:

Content: Updating top nav & adding placeholders pages

---

_includes/footer.html
contact.html
css/custom.css

This pull request fixes #34.
The ask for #34 was to add LinkedIn and YouTube buttons to the site.  It seems that social media buttons currently exist in 2 places.  The footer and on the contact page.
This pull request adds the LinkedIn and YouTube buttons to both the footer and the contact page.  Currently, the way the site was coded, this required updates in 2 different html files.  One place in the `_includes/footer.html` and the other on the `contact.html` page.  Additionally, I noticed a few more responsive issues with the social media icons on the contact page so fixed those issues in this pull request as well.
<kbd>
</kbd>
<kbd>
</kbd>
<kbd>
</kbd>
<kbd>
</kbd>
<kbd>
</kbd>
<kbd>
</kbd>

Feature: Adding LinkedIn & YouTube links

---

css/custom.css
rethinking-rehab.html

This PR fixes #13 by including all of the style changes indicated in the issue.
> Please get rid of the animation and post-it notes. I think it would be more visually appealing and less cumbersome if you just have A or B, static, and on slightly transparent red backgrounds. and then "As it turns out ... " with the tiny little underline thing, and C. None of the Above, on a slightly transparent green background
This item was pretty self explanatory and removed the animations in the CSS file.  I guessed on the exact colors and transparencies based on what I thought looked good, but I am certainly no designer, so happy to adjust if necessary.  Below is how that section now looks:
> Please remove the definitions from being overlaid across the pictures and instead add them as smaller font, …

Styling: Changes to rethinking-rehab page

---

contact.html

This PR includes a fix for the heading centering issue described in #29 .
The problem for this issue is stemming from a class that includes a negative margin that was added to the div above it.  In general, negative margins are not recommended and tend to cause other issues, like the centering issue described in the issue.
As described above, the simplest solution that I can think of is to remove the negative margin class from the div above the issue.  
I'm not sure if a negative margin is actually required here?  I actually think the spacing is more consistent and better without the negative margin?  Screen caps below of before fix (with the negative margin) and after the fix (with the negative margin).  If I am mistaken and the spacing should match as it does before the fix, please let …

Bug Fix: Contact Heading Centering Issue

---

_includes/nav.html
css/custom.css
they-were-here.html

This update fixes #35  that calls for adding a "They Were Here" page under the "About Us" menu.
Below is a screen cap of how the new page is stubbed out to look:

Content: Adding They were here page

---

_includes/nav.html
volunteer.html

This update fixes #39 that calls for adding a submenu under the, now called, "help" top nav item.  One of the submenu items also required a new volunteer page be created with the same content from the get-involved page which you can see in below screen capture:

Content: Creating help submenu & volunteer page

---

css/custom.css

This PR fixes #55 which was a bug where the "About Us" navigational menu item was not being shown.
The solution for this problem was due to, what appears to be, a deliberately placed CSS rule to hide the specifically, 5th menu item on mobile.  I'm not sure the reason behind why such a CSS rule would exist, maybe the 5th menu item broke a previous design or something?
At any rate, I removed the CSS rule in this pull request so the "About Us" menu item will display normally like the other menu items.  Screenshot below with "About Us" submenu expanded:

Bug: Fixing hidden menu nav item

---

_includes/nav.html

This PR fixes #57 that moves the "They Were Here" navigation submenu currently located under "About Us" to it's own distinct nav item called "Remember".

Content: Update main nav with "Remember" option

---

rethinking-rehab.html

This PR fixes #67 for a typo on the rethinking rehab page.  In addition to the typo, I also found a couple other instances where HTML entities weren't used where they probably should be.

Content: Fixing typo for addictions

---

css/custom.css
index.html

This PR fixes and finalizes #58.
The outstanding item in #58 that haven't been addressed in prior pull requests was the task to add a MailChimp subscription form to the home page of the site below the brochure download link.  This PR accomplishes that last remaining item.
- This is the most basic implementation and only requires a user to input their email address.  If other fields are desired, please let me know.
-  Additionally, the most basic implementation will take the user to MailChimp after clicking the submit button.  If any other action is needed, we can adjust that, but it will take additional time obviously.
- Finally, wasn't sure if there was any design in mind for the overall look/feel of the subscription form, so I went with what I thought made the most sense and utilizing …

Feature: Subscription form addition to home page

---

_includes/nav.html
about.html

This issue fixes #76 that detailed some top navigation changes.
Everything is pretty straight forward here, but there wasn't any "content" identified for the new financials icon on the about page.  I used the following copy as placeholder: "Take a look at our financials and documentation for your tax deductions".
Below is a screen capture of the new about page with the financial icon that I choose which was actually already being used on the get-involved page.

Feature: Changes to top navigation

---

_pages/science-of-connection.md
_sections/single/rachel-ted-talk.md

This PR addresses #93 which was to add Rachel's TED talk video to the top of the science-of-connection page.
In order to accomplish this, we simply added a new content section to the science-of-connection page and added the youtube embed code.
Below is a screen capture of viewing it on a desktop browser:

Content: Adding Rachel's TED talk video to science-of-connection page

---

_config.yml
_data/asheville-pilot-program.yaml

This issue is an initial fix for actual bugs found in analysis of #106.  The 2 code fixes included with this fix:
1.  removes the `_pages` directory from being built out so hopefully users would never navigate to an `_pages` directory as was observed in the report shared in #106.
2. fixes a malformed URL on the /our-programs/ page.

BUG: Fixing broken links

---

_data/footer.yaml
_data/header.yaml

This PR address #88 which is to hide the "Program Methodology" navigational item from the "Heal" top nav.
Just an FYI, the "Heal" top nav also links to the `/our-programs/` page and there is also a footer item titled "Our-Programs" that links to `/our-programs/`.  Not sure if it is desired to change the "Heal" link and remove the footer link as well?  
For now, just removed the top nav item per the issue.

Content: Removing "Program Methodology" from the "Heal" top nav

---

_sass/base/_base.scss
_sass/components/_buttons.scss

This PR contains 2 fixes that were found will investigating #107.  I wasn't able to reproduce the issues exactly described in #107, but I the below 2 bugs were found and are fixed with this update:
1. The first issue was identified with the "focus" state of the purple buttons enabled, so one of the included style fixes makes the focus state the same styling as the hover state.
2. The second fix was identified only in Safari browsers and is a known bootstrap bug for multi column flexible layouts.

Bug: Fixing button focus style & safari 3 column layout

---

_includes/sections/double.html
_includes/sections/triple.html
_sections/triple-columns/triple-col-pilot-ctas-2.md
_sections/triple-columns/triple-col-pilot-ctas-3.md

This update fixes #119 that changes the order of the CTA buttons for the Asheville Pilot Program on the home page.  This should've simply been adjusting the `order` field on the content block's yaml, but I also saw there was a small bug in the layouts for the double and triple content blocks incorrectly using `order` as the liquid filter, but it should actually be `sort` so I had to update that as well.

CONTENT: Changing order of Asheville Pilot Program CTAs

---

_sections/single/apply.md
_sections/single/listening-training-authetic-connection.md
_sections/single/listening-training-training.md

This PR fixes #123 that calls for changing the links & text for the listening training button as well as removing the italicized text underneath 2 of the buttons.
Screenshot of content changes:

Content: Changing listening training page buttons

---

_includes/sections/events.html
assets/js/functions.js

This PR adds the ability for upcoming events to expire automatically and be moved to the "Past Events" section on the Events page.
In order to accomplish this task, I added a simple javascript snippet that will check the date on each "Upcoming Event" and compare it to today's date on a user's device.  If the event's date has passed, then that event will be moved to the top of the "Past Events" section on the Events page and hide any "RSVP" call to action buttons for the event.

Feature: Adding event expiration functionality

---

_pages/they-were-here.md

This update addresses #134 which is to add a new header subtext to the memorial page that is also a link.
I wasn't sure where the link should go, but I assumed it should go to the donation page?  So, I made it go there and open in a new tab.  If that isn't the correct page to link to please let me know and I can update the URL.
Below is a screenshot of how the subnav link looks:

Content: Adding donation link to memorial page

---

_sections/single/calendar.md

This PR addresses the issue brought up in this slack conversation: https://seekhealing.slack.com/archives/CE76SU751/p1552152543001900
Unfortunately, I don't think there is 100% optimal fix for this solution with the Google Calendar embed functionality.  There are 2 better options for fixing this issue in my opinion however.  I am detailing both options below, but this PR is for the implementation of option number 2 that I think is better from a usability perspective and what I would recommend for my own site for this.  **_BOTH options do force an "agenda" view of the calendar in mobile screen sizes to maximize the calendar's usability.  Both options also address the immediate concern of being able to see events and open them though._** 
Additionally, if we wanted to use javascript instead …

Bug: Google calendar mobile/responsive fixes

---

_sass/base/_base.scss
_sections/double-columns/travis-test-parts-2.md

This PR fixes a mistake introduced in #264 that duplicated 1 testimonial text twice and omitted one during the restructuring of that content on the home page.  In addition, this also includes a very minor style tweak.
This is for the following Slack conversation:
https://seekhealing.slack.com/archives/CE76SU751/p1560970988000800

Bug: Fixing duplicate testimonial text & style tweak for homepage

---

_data/header.yaml
_data/partners.yml
_includes/sections/partners.html
_pages/partners.md
_sections/partners/conn-agent-partners.md
_sections/partners/strategic-partners.md
_sections/subnav/partners.md

This PR accomplishes 2 more changes from the May 2019 Website Updates document as detailed below:
1. Adds the new Partners Page per the May 2019 Website Updates as detailed [here](https://docs.google.com/document/d/1m4dQ3hz6Rgy3GcJH-0a0VB_Gc55XgGNBJw1Cq4C2bvM/edit?ts=5d1ea632#heading=h.ltuqz6p3c7g).
2. Final and related main navigation changes per the May 2019 Website Updates as detailed [here](https://docs.google.com/document/d/1m4dQ3hz6Rgy3GcJH-0a0VB_Gc55XgGNBJw1Cq4C2bvM/edit?ts=5cf92b1a#heading=h.fh01erohz7zu) that include:
- Please add a new page to the ABOUT menu called “Partners”
- Please add each of the sub-pages in a drop-down menu from the “ABOUT” button

May 2019 Updates: New Partners page, & final navigation updates

---

_includes/sections/subnav.html
_pages/learn.md
_sections/subnav/additional-resources.md
_sections/subnav/harm-reduction.md

This PR completes the edits requested in the "July 2019 Cleanup Edits" document for the Learn(/learn/) page that include the following:
1. Please change the order of the buttons and make the Additional Resources icon the last one (after Harm Reduction)
2. Please remove “You can’t heal in the same environment where you got sick” (no replacement)

July 2019 Updates: Learn page

---

_sections/single/extra-care-program.md
_sections/single/extra-care-qualifications.md
_sections/single/start-conversation.md

This PR completes the edits requested in the "July 2019 Cleanup Edits" document for the Extra Care Program(/extra-care-program/) page that include the following:
1. Please change:
> If you’re currently trying to make a major change to your relationship with a certain drug or chemical, you may qualify for SeekHealing’s Extra Care Program scholarships.
To:
> Free services to support healing from trauma and addiction for those at risk for overdose.
> If you’ve ever been bonded to opioids or amphetamines and you’ve either: 
>   - used in the last six months,
>   - experienced major life transition, or
>   - had a medical crisis 
> … you may qualify for free program services. The program provides ongoing aftercare and support whether you have never gone through treatment, are currently in …

July 2019 Updates: Extra Care Program page

---

_sections/single/listening-training-authetic-connection.md
_sections/single/listening-training-intro.md

This PR completes the edits requested in the "July 2019 Cleanup Edits" document for the Listening Training(/listening-training/) page that include the following:
1. change 
> Join us for 16 hours of professional training in authentic human connection and peer-based addiction support. It’s a one-of-a-kind opportunity to dig deeper into your own personal growth & healing journey while lifting others up along the way.
to:
> Practical training in active listening: the foundation for more meaningful connection with others. This course teaches you how to better listen to others, and yourself. It’s a one-of-a-kind opportunity to dig deeper into your own personal growth & healing journey while lifting others up along the way. 
> Offered as a 6-week series (email megan@seekhealing.org for next …

July 2019 Updates: Listening Training page

---

_data/footer.yaml
_includes/sections/social-share.html
_sass/components/_forms.scss
_sass/layouts/_sections.scss
assets/js/custom-functions.js

This PR contains 3 fixes (2 bugs, 1 change) each within their own commit if it is desired to pull any of these out. The fixes are detailed as below:
1. A simple link fix for the 'Get Involved' footer link that was pointing to '/get-involved/' but should be pointing to '/help/'.
2. A change in the fundraiser progress bar logic, so that if the amount raised isn't above $250 yet, it will still use $250 as a baseline minimum.  It should also be noted, that this logic truncates the percentage showing in the meter to an integer as opposed to showing decimal points.  So $250 raised out of $10,000 will show as 2% instead of 3%.
3. Finally, there is some mobile styling cleanup included in the last commit made.  The most egregious styling fix is shown below with a before/after for the holiday …

Bugs: Miscellaneous cleanup bugfixes

---

_includes/sections/hero.html
_sections/hero/home.md
_sections/single/elevator-pitch.md

This PR removes the donation form entirely from the homepage hero and puts a simple donation button and video back into the hero as it looked similarly prior to the donation form being placed there.  This is per Slack Conversation: https://seekhealing.slack.com/archives/GRKUSLSMV/p1577114769004100
Screen shot of new homepage hero with removal of donation form and donation button/video back in the hero:

Removing donation form from Homepage Hero

---

_pages/index.md

This PR removes the social sharing clips from the homepage per: https://seekhealing.slack.com/archives/CE76SU751/p1583337479000300.
I did decide to keep the "main-share" partial in the codebase as well as the styling around this in case this need comes back, but if it is desired to remove all of that from the codebase altogether, let me know.  Really, I'd recommend doing this if the social sharing clips will never come back or be re-utilized in the future.

Content: Removing social shares from the home page
